package edu.iastate.cs228.hw3;

import java.io.FileNotFoundException;

/**
 *  
 * @author Gavin Monroe
 *
 */

public class PuzzleSolver 
{
	/**
	 *  Read an initial state from an file.  Solve the eight puzzle using two heuristics based on 
	 *  the number of mismatched tiles and the Manhattan distance.  Each solution is printed out 
	 *  as a sequence of states, generated by single moves, from the initial state to the goal
	 *  state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
	public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException
	{
		// Read an initial board configuration from a file.
		State puzzle = new State(args[0]);

		// Call EightPuzzle.solve8puzzle() to solve the puzzle.
		String solution = EightPuzzle.solve8Puzzle(puzzle);
		if (solution == null){
			System.out.println("No solution exists for the following initial state:");
			System.out.println();
			System.out.println(puzzle);
		}else{
			System.out.println(solution);
		}
	}

}
